[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.pylint]
max-line-length = 120
disable = ["missing-module-docstring", "too-few-public-methods"]
ignore-paths = "migrations"

[tool.flake8]
max-line-length = 120
